### ISSUE TITLE
Cinder boot to volume is broken

### ISSUE THREAD

**Issue by cloudnull** [rcbops/ansible-lxc-rpc#120]
Booting a nova VM to a cinder volume results in Error. This error is related to [ https://github.com/rcbops/ansible-lxc-rpc/issues/113 ] and is resolved when installing `python-glanceclient==0.13.1`.  

This is the error as reported by nova.

``` bash
Error: Failed to launch instance "test": Please try again later [Error: Block Device Mapping is Invalid.].
```

From the Cinder-API logs this is the stack trace:

``` bash
2014-09-12 23:28:40.721 2273 ERROR cinder.api.middleware.fault [req-2c5097aa-d652-4232-a3ec-0b58fb2ad211 714758b62c684f66a71e7fd1a86592fc 43d59e0674b84fd6b7da7ed59fc569b4 - - -] Caught error: No module named v1.client
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault Traceback (most recent call last):
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/cinder/api/middleware/fault.py", line 75, in __call__
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     return req.get_response(self.application)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1320, in send
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     application, catch_exc_info=False)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1284, in call_application
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     app_iter = application(self.environ, start_response)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 144, in __call__
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     return resp(environ, start_response)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/keystonemiddleware/auth_token.py", line 565, in __call__
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     return self._app(env, start_response)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 144, in __call__
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     return resp(environ, start_response)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 144, in __call__
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     return resp(environ, start_response)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/routes/middleware.py", line 131, in __call__
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     response = self.app(environ, start_response)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 144, in __call__
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     return resp(environ, start_response)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 130, in __call__
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     resp = self.call_func(req, *args, **self.kwargs)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 195, in call_func
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     return self.func(req, *args, **kwargs)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/cinder/api/openstack/wsgi.py", line 895, in __call__
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     content_type, body, accept)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/cinder/api/openstack/wsgi.py", line 943, in _process_stack
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     action_result = self.dispatch(meth, request, action_args)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/cinder/api/openstack/wsgi.py", line 1019, in dispatch
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     return method(req=request, **action_args)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/cinder/api/v1/volumes.py", line 385, in create
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     **kwargs)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/cinder/volume/api.py", line 189, in create
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     flow_engine.run()
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/taskflow/utils/lock_utils.py", line 53, in wrapper
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     return f(*args, **kwargs)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/taskflow/engines/action_engine/engine.py", line 111, in run
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     self._run()
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/taskflow/engines/action_engine/engine.py", line 121, in _run
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     self._revert(misc.Failure())
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/taskflow/engines/action_engine/engine.py", line 78, in _revert
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     misc.Failure.reraise_if_any(failures.values())
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/taskflow/utils/misc.py", line 558, in reraise_if_any
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     failures[0].reraise()
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/taskflow/utils/misc.py", line 565, in reraise
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     six.reraise(*self._exc_info)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/taskflow/engines/action_engine/executor.py", line 36, in _execute_task
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     result = task.execute(**arguments)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/cinder/volume/flows/api/create_volume.py", line 341, in execute
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     self._check_image_metadata(context, image_id, size)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/cinder/volume/flows/api/create_volume.py", line 180, in _check_image_metadata
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     image_meta = self.image_service.show(context, image_id)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/cinder/image/glance.py", line 223, in show
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     _reraise_translated_image_exception(image_id)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/cinder/image/glance.py", line 221, in show
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     image = self._client.call(context, 'get', image_id)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/cinder/image/glance.py", line 156, in call
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     version)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/cinder/image/glance.py", line 137, in _create_onetime_client
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     self.use_ssl, version)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/cinder/image/glance.py", line 85, in _create_glance_client
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault     return glanceclient.Client(str(version), endpoint, **params)
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/glanceclient/client.py", line 20, in Client
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/glanceclient/common/utils.py", line 210, in import_versioned_module
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault   File "/usr/local/lib/python2.7/dist-packages/glanceclient/openstack/common/importutils.py", line 57, in import_module
2014-09-12 23:28:40.721 2273 TRACE cinder.api.middleware.fault ImportError: No module named v1.client
```

**Comment by cloudnull** [comment]
Fixing the glance client with ansible resolves this problem:

`bash
ansible all_containers -m shell -a "pip uninstall -y python-glanceclient"
ansible all_containers -m shell -a "pip install python-glanceclient==0.13.1"
`

![screen shot 2014-09-12 at 18 38 24](https://cloud.githubusercontent.com/assets/2066292/4258607/4b248708-3ad6-11e4-8ba8-8298bf002fbb.png)
![screen shot 2014-09-12 at 18 40 21](https://cloud.githubusercontent.com/assets/2066292/4258608/4b2dc55c-3ad6-11e4-8474-6c11f199af62.png)
