### ISSUE TITLE
no-index = true flag inside .pip/pip.conf breaks installation of pip within containers

### ISSUE THREAD

**Issue by madorn** [rcbops/ansible-lxc-rpc#139]
The `no-index = true` flag inside `.pip/pip.conf` appears to be breaking installation of pip during `setup/rolescommon/tasks/get_pip.yml`

Setting this to `no-index = false` seems to resolve the issue.

Error when set to true:  

`
Exception:
Traceback (most recent call last):
  File "/tmp/tmpKMTJtq/pip.zip/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/tmp/tmpKMTJtq/pip.zip/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/tmp/tmpKMTJtq/pip.zip/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/tmp/tmpKMTJtq/pip.zip/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/tmp/tmpKMTJtq/pip.zip/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/tmp/tmpKMTJtq/pip.zip/pip/util.py", line 621, in unpack_file
    unzip_file(filename, location, flatten=not filename.endswith(('.pybundle', '.whl')))
  File "/tmp/tmpKMTJtq/pip.zip/pip/util.py", line 491, in unzip_file
    zip = zipfile.ZipFile(zipfp)
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
`

**Comment by cloudnull** [comment]
This looks like the download of one of the pip dependencies failed which resulted failure. I've now attempted to recreate the issue several times and have had no success. Could you provide more details on the following: 
- What container had the issues or was it all containers? 
- Did the error effect all containers? 
- Was this a new container?
- Was this a new installation?

**Comment by madorn** [comment]
-all containers had the issue
-yes, the error affects all containers.
-new installation - specifically running container_common.yml during the setup process.

i will pull from master again and attempt to recreate.

**Comment by madorn** [comment]
issue does not occur when deploying in public cloud.

closing.
