### ISSUE TITLE
nova_setup | Perform a Nova DB sync: OperationalError: (OperationalError) (1050, "Table 'instances' already exists") after playbook retry

### ISSUE THREAD

**Issue by uksysadmin** [rcbops/ansible-lxc-rpc#173]
I get the following when I run playbooks/openstack/openstack-common.yml after running the playbook again with retry.

My environment: openstack4,5+6 are my infrastructure nodes. Mariadb/Galera all working fine.
This is after a previous error, and after another retry, so assuming this nova-manage db sync has already run and causing problems when run again (though seems more of a feature of OpenStack than our playbooks. Juju folk noted a similar error: https://bugs.launchpad.net/charms/+source/nova-cloud-controller/+bug/1335139).

root@openstack7:~/ansible-lxc-rpc/rpc_deployment# mysql -uroot -p -h192.168.1.107 -Dnova -e 'show tables;'
Enter password: 
+-------------------------------------+
| Tables_in_nova                      |
+-------------------------------------+
| agent_builds                        |
| aggregate_hosts                     |
| aggregate_metadata                  |
| aggregates                          |
...
| instances                           |
| iscsi_targets                       |
| key_pairs                           |
| migrate_version                     |
...

Output of error:

TASK: [nova_setup | Perform a Nova DB sync] **********************************\* 
failed: [openstack6_nova_api_os_compute_container-bbaff90e] => {"changed": true, "cmd": ["nova-manage", "db", "sync"], "delta": "0:00:03.277244", "end": "2014-09-26 08:51:27.800544", "rc": 1, "start": "2014-09-26 08:51:24.523300"}
stderr: 2014-09-26 08:51:27.460 2603 INFO migrate.versioning.api [-] 215 -> 216... 
2014-09-26 08:51:27.585 2603 CRITICAL nova [-] OperationalError: (OperationalError) (1050, "Table 'instances' already exists") "\nCREATE TABLE instances (\n\tcreated_at DATETIME, \n\tupdated_at DATETIME, \n\tdeleted_at DATETIME, \n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tinternal_id INTEGER, \n\tuser_id VARCHAR(255), \n\tproject_id VARCHAR(255), \n\timage_ref VARCHAR(255), \n\tkernel_id VARCHAR(255), \n\tramdisk_id VARCHAR(255), \n\tlaunch_index INTEGER, \n\tkey_name VARCHAR(255), \n\tkey_data MEDIUMTEXT, \n\tpower_state INTEGER, \n\tvm_state VARCHAR(255), \n\tmemory_mb INTEGER, \n\tvcpus INTEGER, \n\thostname VARCHAR(255), \n\thost VARCHAR(255), \n\tuser_data MEDIUMTEXT, \n\treservation_id VARCHAR(255), \n\tscheduled_at DATETIME, \n\tlaunched_at DATETIME, \n\tterminated_at DATETIME, \n\tdisplay_name VARCHAR(255), \n\tdisplay_description VARCHAR(255), \n\tavailability_zone VARCHAR(255), \n\tlocked BOOL, \n\tos_type VARCHAR(255), \n\tlaunched_on MEDIUMTEXT, \n\tinstance_type_id INTEGER, \n\tvm_mode VARCHAR(255), \n\tuuid VARCHAR(36), \n\tarchitecture VARCHAR(255), \n\troot_device_name VARCHAR(255), \n\taccess_ip_v4 VARCHAR(39), \n\taccess_ip_v6 VARCHAR(39), \n\tconfig_drive VARCHAR(255), \n\ttask_state VARCHAR(255), \n\tdefault_ephemeral_device VARCHAR(255), \n\tdefault_swap_device VARCHAR(255), \n\tprogress INTEGER, \n\tauto_disk_config BOOL, \n\tshutdown_terminate BOOL, \n\tdisable_terminate BOOL, \n\troot_gb INTEGER, \n\tephemeral_gb INTEGER, \n\tcell_name VARCHAR(255), \n\tnode VARCHAR(255), \n\tdeleted INTEGER, \n\tlocked_by ENUM('owner','admin'), \n\tcleaned INTEGER, \n\tPRIMARY KEY (id), \n\tCHECK (locked IN (0, 1)), \n\tCHECK (auto_disk_config IN (0, 1)), \n\tCHECK (shutdown_terminate IN (0, 1)), \n\tCHECK (disable_terminate IN (0, 1))\n)ENGINE=InnoDB CHARSET=utf8\n\n" ()
2014-09-26 08:51:27.585 2603 TRACE nova Traceback (most recent call last):
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/bin/nova-manage", line 10, in <module>
2014-09-26 08:51:27.585 2603 TRACE nova     sys.exit(main())
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/nova/cmd/manage.py", line 1376, in main
2014-09-26 08:51:27.585 2603 TRACE nova     ret = fn(_fn_args, *_fn_kwargs)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/nova/cmd/manage.py", line 885, in sync
2014-09-26 08:51:27.585 2603 TRACE nova     return migration.db_sync(version)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/nova/db/migration.py", line 29, in db_sync
2014-09-26 08:51:27.585 2603 TRACE nova     return IMPL.db_sync(version=version)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/nova/db/sqlalchemy/migration.py", line 44, in db_sync
2014-09-26 08:51:27.585 2603 TRACE nova     return versioning_api.upgrade(get_engine(), repository, version)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/migrate/versioning/api.py", line 186, in upgrade
2014-09-26 08:51:27.585 2603 TRACE nova     return _migrate(url, repository, version, upgrade=True, err=err, **opts)
2014-09-26 08:51:27.585 2603 TRACE nova   File "<string>", line 2, in _migrate
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/migrate/versioning/util/__init__.py", line 160, in with_engine
2014-09-26 08:51:27.585 2603 TRACE nova     return f(_a, *_kw)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/migrate/versioning/api.py", line 366, in _migrate
2014-09-26 08:51:27.585 2603 TRACE nova     schema.runchange(ver, change, changeset.step)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/migrate/versioning/schema.py", line 93, in runchange
2014-09-26 08:51:27.585 2603 TRACE nova     change.run(self.engine, step)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/migrate/versioning/script/py.py", line 148, in run
2014-09-26 08:51:27.585 2603 TRACE nova     script_func(engine)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/nova/db/sqlalchemy/migrate_repo/versions/216_havana.py", line 1071, in upgrade
2014-09-26 08:51:27.585 2603 TRACE nova     instances.create()
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/schema.py", line 655, in create
2014-09-26 08:51:27.585 2603 TRACE nova     checkfirst=checkfirst)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1617, in _run_visitor
2014-09-26 08:51:27.585 2603 TRACE nova     conn._run_visitor(visitorcallable, element, *_kwargs)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1246, in _run_visitor
2014-09-26 08:51:27.585 2603 TRACE nova     *_kwargs).traverse_single(element)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 120, in traverse_single
2014-09-26 08:51:27.585 2603 TRACE nova     return meth(obj, **kw)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 732, in visit_table
2014-09-26 08:51:27.585 2603 TRACE nova     self.connection.execute(CreateTable(table))
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
2014-09-26 08:51:27.585 2603 TRACE nova     return meth(self, multiparams, params)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 69, in _execute_on_connection
2014-09-26 08:51:27.585 2603 TRACE nova     return connection._execute_ddl(self, multiparams, params)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 783, in _execute_ddl
2014-09-26 08:51:27.585 2603 TRACE nova     compiled
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
2014-09-26 08:51:27.585 2603 TRACE nova     context)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
2014-09-26 08:51:27.585 2603 TRACE nova     exc_info
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
2014-09-26 08:51:27.585 2603 TRACE nova     reraise(type(exception), exception, tb=exc_tb)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
2014-09-26 08:51:27.585 2603 TRACE nova     context)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
2014-09-26 08:51:27.585 2603 TRACE nova     cursor.execute(statement, parameters)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
2014-09-26 08:51:27.585 2603 TRACE nova     self.errorhandler(self, exc, value)
2014-09-26 08:51:27.585 2603 TRACE nova   File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
2014-09-26 08:51:27.585 2603 TRACE nova     raise errorclass, errorvalue
2014-09-26 08:51:27.585 2603 TRACE nova OperationalError: (OperationalError) (1050, "Table 'instances' already exists") "\nCREATE TABLE instances (\n\tcreated_at DATETIME, \n\tupdated_at DATETIME, \n\tdeleted_at DATETIME, \n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tinternal_id INTEGER, \n\tuser_id VARCHAR(255), \n\tproject_id VARCHAR(255), \n\timage_ref VARCHAR(255), \n\tkernel_id VARCHAR(255), \n\tramdisk_id VARCHAR(255), \n\tlaunch_index INTEGER, \n\tkey_name VARCHAR(255), \n\tkey_data MEDIUMTEXT, \n\tpower_state INTEGER, \n\tvm_state VARCHAR(255), \n\tmemory_mb INTEGER, \n\tvcpus INTEGER, \n\thostname VARCHAR(255), \n\thost VARCHAR(255), \n\tuser_data MEDIUMTEXT, \n\treservation_id VARCHAR(255), \n\tscheduled_at DATETIME, \n\tlaunched_at DATETIME, \n\tterminated_at DATETIME, \n\tdisplay_name VARCHAR(255), \n\tdisplay_description VARCHAR(255), \n\tavailability_zone VARCHAR(255), \n\tlocked BOOL, \n\tos_type VARCHAR(255), \n\tlaunched_on MEDIUMTEXT, \n\tinstance_type_id INTEGER, \n\tvm_mode VARCHAR(255), \n\tuuid VARCHAR(36), \n\tarchitecture VARCHAR(255), \n\troot_device_name VARCHAR(255), \n\taccess_ip_v4 VARCHAR(39), \n\taccess_ip_v6 VARCHAR(39), \n\tconfig_drive VARCHAR(255), \n\ttask_state VARCHAR(255), \n\tdefault_ephemeral_device VARCHAR(255), \n\tdefault_swap_device VARCHAR(255), \n\tprogress INTEGER, \n\tauto_disk_config BOOL, \n\tshutdown_terminate BOOL, \n\tdisable_terminate BOOL, \n\troot_gb INTEGER, \n\tephemeral_gb INTEGER, \n\tcell_name VARCHAR(255), \n\tnode VARCHAR(255), \n\tdeleted INTEGER, \n\tlocked_by ENUM('owner','admin'), \n\tcleaned INTEGER, \n\tPRIMARY KEY (id), \n\tCHECK (locked IN (0, 1)), \n\tCHECK (auto_disk_config IN (0, 1)), \n\tCHECK (shutdown_terminate IN (0, 1)), \n\tCHECK (disable_terminate IN (0, 1))\n)ENGINE=InnoDB CHARSET=utf8\n\n" ()
2014-09-26 08:51:27.585 2603 TRACE nova 
stdout: Command failed, please check log for more info

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/nova-all.retry

openstack6_nova_api_os_compute_container-bbaff90e : ok=49   changed=5    unreachable=0    failed=1

**Comment by claco** [comment]
@uksysadmin Is this on master, or 9.0.0?

**Comment by uksysadmin** [comment]
9.0.0

**Comment by claco** [comment]
Just a few thoughts. Digging for context. First, I assume this is using haproxy as the lb? (Can you post your user_config?) That launchpad seems to imply some form of locking/deadlock issue, where all 3 intra nodes are trying to run something against galera at the same time. I've see that page before, and I'd think we would've seen this by now in labs since we rerun the entire stack of playbooks all of the time

"This is after a previous error". What was the previous error? Was it the same error?

**Comment by uksysadmin** [comment]
Yes this is haproxy. user_config: http://paste.openstack.org/show/wDG4A6CTnsfOMZ8E13AP/
Previous error, probably something around container timeout [slow hardware/something, didn't seem related - but forced me to do a retry].

**Comment by cloudnull** [comment]
This issue is likely due to the sqlalchemy-migrate version 0.9.2 being determined to break nova. This was a recent change in global requirements. Related PR: https://github.com/openstack/requirements/commit/ab78b6645b3a63f9f5b0c89ebb84135a331aea38. We have corrected this in the "stable/icehouse" branch and the change should make it in for 9.0.1.  Being that this is a versioning issue and does not effect "master" and has been resolved in "stable/icehouse" I am closing this issue. Should it crop up again please feel free to reopen this issue.
