### ISSUE TITLE
Repo add timeout

### ISSUE THREAD

**Issue by hughsaunders** [rcbops/ansible-lxc-rpc#445]
http://jenkins.propter.net/job/dev-sat6-gate/211/consoleFull

```
16:31:00 TASK: [container_common | Add Container repos] ******************************** 
16:31:08 changed: [node25_rsyslog_container-95683824] => (item={'repo': 'ppa:adiscon/v8-stable', 'state': 'present'})
16:31:08 changed: [node24_rsyslog_container-6cb048be] => (item={'repo': 'ppa:adiscon/v8-stable', 'state': 'present'})
16:31:08 changed: [node27_rsyslog_container-326fdea3] => (item={'repo': 'ppa:adiscon/v8-stable', 'state': 'present'})
16:31:08 changed: [node26_rsyslog_container-c087f142] => (item={'repo': 'ppa:adiscon/v8-stable', 'state': 'present'})
16:31:12 failed: [node23_rsyslog_container-ec8e7d32] => (item={'repo': 'ppa:adiscon/v8-stable', 'state': 'present'}) => {"failed": true, "item": {"repo": "ppa:adiscon/v8-stable", "state": "present"}, "parsed": false}
16:31:12 invalid output was: Traceback (most recent call last):
16:31:12   File "<stdin>", line 2071, in <module>
16:31:12   File "<stdin>", line 408, in main
16:31:12   File "<stdin>", line 343, in add_source
16:31:12   File "<stdin>", line 322, in _get_ppa_info
16:31:12   File "<stdin>", line 2058, in fetch_url
16:31:12   File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
16:31:12     return _opener.open(url, data, timeout)
16:31:12   File "/usr/lib/python2.7/urllib2.py", line 404, in open
16:31:12     response = self._open(req, data)
16:31:12   File "/usr/lib/python2.7/urllib2.py", line 422, in _open
16:31:12     '_open', req)
16:31:12   File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
16:31:12     result = func(*args)
16:31:12   File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
16:31:12     return self.do_open(httplib.HTTPSConnection, req)
16:31:12   File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
16:31:12     r = h.getresponse(buffering=True)
16:31:12   File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
16:31:12     response.begin()
16:31:12   File "/usr/lib/python2.7/httplib.py", line 409, in begin
16:31:12     version, status, reason = self._read_status()
16:31:12   File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
16:31:12     line = self.fp.readline(_MAXLINE + 1)
16:31:12   File "/usr/lib/python2.7/socket.py", line 476, in readline
16:31:12     data = self._sock.recv(self._rbufsize)
16:31:12   File "/usr/lib/python2.7/ssl.py", line 341, in recv
16:31:12     return self.read(buflen)
16:31:12   File "/usr/lib/python2.7/ssl.py", line 260, in read
16:31:12     return self._sslobj.read(len)
16:31:12 ssl.SSLError: The read operation timed out
16:31:12 
```

Maybe needs a retry.

**Comment by cloudnull** [comment]
+1 I think that this method should have a retry on it.
