### ISSUE TITLE
[keystone] keystone db-sync fails on 9.0.1 -> 10.0.0 upgrade

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/ansible-lxc-rpc#461]
```
TASK: [keystone_setup | Perform a Keystone DB sync] *************************** 
failed: [node91_keystone_container-c63d88c6] => {"changed": true, "cmd": ["keystone-manage", "db_sync"], "delta": "0:00:11.853116", "end": "2014-11-04 15:26:02.357877", "rc": 1, "start": "2014-11-04 15:25:50.504761"}
stderr: 2014-11-04 15:25:51.039 7948 INFO migrate.versioning.api [-] 54 -> 55... 
2014-11-04 15:26:02.298 7948 CRITICAL keystone [-] OperationalError: (OperationalError) (1061, "Duplicate key name 'ix_token_user_id'") 'CREATE INDEX ix_token_user_id ON token (user_id)' ()
2014-11-04 15:26:02.298 7948 TRACE keystone Traceback (most recent call last):
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/bin/keystone-manage", line 44, in <module>
2014-11-04 15:26:02.298 7948 TRACE keystone     cli.main(argv=sys.argv, config_files=config_files)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/keystone/cli.py", line 307, in main
2014-11-04 15:26:02.298 7948 TRACE keystone     CONF.command.cmd_class.main()
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/keystone/cli.py", line 74, in main
2014-11-04 15:26:02.298 7948 TRACE keystone     migration_helpers.sync_database_to_version(extension, version)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/keystone/common/sql/migration_helpers.py", line 204, in sync_database_to_version
2014-11-04 15:26:02.298 7948 TRACE keystone     _sync_common_repo(version)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/keystone/common/sql/migration_helpers.py", line 160, in _sync_common_repo
2014-11-04 15:26:02.298 7948 TRACE keystone     init_version=init_version)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/oslo/db/sqlalchemy/migration.py", line 79, in db_sync
2014-11-04 15:26:02.298 7948 TRACE keystone     return versioning_api.upgrade(engine, repository, version)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/migrate/versioning/api.py", line 186, in upgrade
2014-11-04 15:26:02.298 7948 TRACE keystone     return _migrate(url, repository, version, upgrade=True, err=err, **opts)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "<string>", line 2, in _migrate
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/migrate/versioning/util/__init__.py", line 160, in with_engine
2014-11-04 15:26:02.298 7948 TRACE keystone     return f(*a, **kw)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/migrate/versioning/api.py", line 366, in _migrate
2014-11-04 15:26:02.298 7948 TRACE keystone     schema.runchange(ver, change, changeset.step)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/migrate/versioning/schema.py", line 93, in runchange
2014-11-04 15:26:02.298 7948 TRACE keystone     change.run(self.engine, step)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/migrate/versioning/script/py.py", line 148, in run
2014-11-04 15:26:02.298 7948 TRACE keystone     script_func(engine)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/keystone/common/sql/migrate_repo/versions/055_add_indexes_to_token_table.py", line 24, in upgrade
2014-11-04 15:26:02.298 7948 TRACE keystone     sql.Index('ix_token_user_id', token.c.user_id).create()
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/schema.py", line 2908, in create
2014-11-04 15:26:02.298 7948 TRACE keystone     bind._run_visitor(ddl.SchemaGenerator, self)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1617, in _run_visitor
2014-11-04 15:26:02.298 7948 TRACE keystone     conn._run_visitor(visitorcallable, element, **kwargs)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1246, in _run_visitor
2014-11-04 15:26:02.298 7948 TRACE keystone     **kwargs).traverse_single(element)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 120, in traverse_single
2014-11-04 15:26:02.298 7948 TRACE keystone     return meth(obj, **kw)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 748, in visit_index
2014-11-04 15:26:02.298 7948 TRACE keystone     self.connection.execute(CreateIndex(index))
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
2014-11-04 15:26:02.298 7948 TRACE keystone     return meth(self, multiparams, params)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 69, in _execute_on_connection
2014-11-04 15:26:02.298 7948 TRACE keystone     return connection._execute_ddl(self, multiparams, params)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 783, in _execute_ddl
2014-11-04 15:26:02.298 7948 TRACE keystone     compiled
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
2014-11-04 15:26:02.298 7948 TRACE keystone     context)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1156, in _handle_dbapi_exception
2014-11-04 15:26:02.298 7948 TRACE keystone     util.raise_from_cause(newraise, exc_info)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
2014-11-04 15:26:02.298 7948 TRACE keystone     reraise(type(exception), exception, tb=exc_tb)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
2014-11-04 15:26:02.298 7948 TRACE keystone     context)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
2014-11-04 15:26:02.298 7948 TRACE keystone     cursor.execute(statement, parameters)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
2014-11-04 15:26:02.298 7948 TRACE keystone     self.errorhandler(self, exc, value)
2014-11-04 15:26:02.298 7948 TRACE keystone   File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
2014-11-04 15:26:02.298 7948 TRACE keystone     raise errorclass, errorvalue
2014-11-04 15:26:02.298 7948 TRACE keystone OperationalError: (OperationalError) (1061, "Duplicate key name 'ix_token_user_id'") 'CREATE INDEX ix_token_user_id ON token (user_id)' ()
2014-11-04 15:26:02.298 7948 TRACE keystone 

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/openstack-setup.retry

node119_keystone_container-d697072d : ok=37   changed=2    unreachable=0    failed=0   
node121_keystone_container-eef23cc6 : ok=37   changed=2    unreachable=0    failed=0   
node91_keystone_container-c63d88c6 : ok=46   changed=3    unreachable=0    failed=1   
```

looks like we have a duplacate key entry

i would dive deeper but i am in a summit meeting

**Comment by mattt416** [comment]
Hi @jacobwagner,

I just tried upgrading keystone from 9.0.3 to 10.0.0rc4 and could not replicate this.  The db sync task completed fine:

```
TASK: [keystone_setup | Perform a Keystone DB sync] ***************************
changed: [heat-controller-1_keystone_container-a98eeb39]
```

Also, I see two sets of db migrations in the keystone log:

```
2014-11-21 13:10:43.808 1225 INFO migrate.versioning.api [-] 0 -> 1...
2014-11-21 13:10:43.988 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:43.989 1225 INFO migrate.versioning.api [-] 1 -> 2...
2014-11-21 13:10:44.048 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:44.048 1225 INFO migrate.versioning.api [-] 2 -> 3...
2014-11-21 13:10:44.111 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:44.112 1225 INFO migrate.versioning.api [-] 3 -> 4...
2014-11-21 13:10:44.184 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:44.185 1225 INFO migrate.versioning.api [-] 4 -> 5...
2014-11-21 13:10:44.291 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:44.291 1225 INFO migrate.versioning.api [-] 5 -> 6...
2014-11-21 13:10:44.327 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:44.328 1225 INFO migrate.versioning.api [-] 6 -> 7...
2014-11-21 13:10:44.448 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:44.448 1225 INFO migrate.versioning.api [-] 7 -> 8...
2014-11-21 13:10:44.478 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:44.478 1225 INFO migrate.versioning.api [-] 8 -> 9...
2014-11-21 13:10:44.576 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:44.576 1225 INFO migrate.versioning.api [-] 9 -> 10...
2014-11-21 13:10:44.623 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:44.623 1225 INFO migrate.versioning.api [-] 10 -> 11...
2014-11-21 13:10:44.714 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:44.715 1225 INFO migrate.versioning.api [-] 11 -> 12...
2014-11-21 13:10:44.757 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:44.758 1225 INFO migrate.versioning.api [-] 12 -> 13...
2014-11-21 13:10:44.837 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:44.837 1225 INFO migrate.versioning.api [-] 13 -> 14...
2014-11-21 13:10:44.947 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:44.947 1225 INFO migrate.versioning.api [-] 14 -> 15...
2014-11-21 13:10:45.141 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:45.141 1225 INFO migrate.versioning.api [-] 15 -> 16...
2014-11-21 13:10:45.302 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:45.302 1225 INFO migrate.versioning.api [-] 16 -> 17...
2014-11-21 13:10:45.394 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:45.395 1225 INFO migrate.versioning.api [-] 17 -> 18...
2014-11-21 13:10:45.481 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:45.481 1225 INFO migrate.versioning.api [-] 18 -> 19...
2014-11-21 13:10:45.518 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:45.518 1225 INFO migrate.versioning.api [-] 19 -> 20...
2014-11-21 13:10:45.581 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:45.581 1225 INFO migrate.versioning.api [-] 20 -> 21...
2014-11-21 13:10:45.630 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:45.631 1225 INFO migrate.versioning.api [-] 21 -> 22...
2014-11-21 13:10:45.659 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:45.660 1225 INFO migrate.versioning.api [-] 22 -> 23...
2014-11-21 13:10:45.728 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:45.728 1225 INFO migrate.versioning.api [-] 23 -> 24...
2014-11-21 13:10:45.765 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:45.765 1225 INFO migrate.versioning.api [-] 24 -> 25...
2014-11-21 13:10:45.814 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:45.814 1225 INFO migrate.versioning.api [-] 25 -> 26...
2014-11-21 13:10:45.941 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:45.941 1225 INFO migrate.versioning.api [-] 26 -> 27...
2014-11-21 13:10:46.015 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:46.015 1225 INFO migrate.versioning.api [-] 27 -> 28...
2014-11-21 13:10:46.031 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:46.031 1225 INFO migrate.versioning.api [-] 28 -> 29...
2014-11-21 13:10:46.091 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:46.092 1225 INFO migrate.versioning.api [-] 29 -> 30...
2014-11-21 13:10:46.107 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:46.107 1225 INFO migrate.versioning.api [-] 30 -> 31...
2014-11-21 13:10:46.148 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:46.148 1225 INFO migrate.versioning.api [-] 31 -> 32...
2014-11-21 13:10:46.188 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:46.188 1225 INFO migrate.versioning.api [-] 32 -> 33...
2014-11-21 13:10:46.230 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:46.230 1225 INFO migrate.versioning.api [-] 33 -> 34...
2014-11-21 13:10:46.278 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:46.278 1225 INFO migrate.versioning.api [-] 34 -> 35...
2014-11-21 13:10:46.321 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:46.321 1225 INFO migrate.versioning.api [-] 35 -> 36...
2014-11-21 13:10:46.352 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:46.353 1225 INFO migrate.versioning.api [-] 36 -> 37...
2014-11-21 13:10:46.385 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:46.385 1225 INFO migrate.versioning.api [-] 37 -> 38...
2014-11-21 13:10:46.440 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:46.441 1225 INFO migrate.versioning.api [-] 38 -> 39...
2014-11-21 13:10:46.535 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:46.535 1225 INFO migrate.versioning.api [-] 39 -> 40...
2014-11-21 13:10:46.626 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:46.626 1225 INFO migrate.versioning.api [-] 40 -> 41...
2014-11-21 13:10:46.664 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:46.665 1225 INFO migrate.versioning.api [-] 41 -> 42...
2014-11-21 13:10:46.722 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:46.723 1225 INFO migrate.versioning.api [-] 42 -> 43...
2014-11-21 13:10:46.743 1225 INFO migrate.versioning.api [-] done
2014-11-21 13:10:46.744 1225 INFO migrate.versioning.api [-] 43 -> 44...
2014-11-21 13:10:46.794 1225 INFO migrate.versioning.api [-] done
```

... and then:

```
2014-11-21 14:24:06.294 4028 INFO migrate.versioning.api [-] 44 -> 45...
2014-11-21 14:24:06.309 4028 INFO migrate.versioning.api [-] done
2014-11-21 14:24:06.310 4028 INFO migrate.versioning.api [-] 45 -> 46...
2014-11-21 14:24:06.324 4028 INFO migrate.versioning.api [-] done
2014-11-21 14:24:06.324 4028 INFO migrate.versioning.api [-] 46 -> 47...
2014-11-21 14:24:06.340 4028 INFO migrate.versioning.api [-] done
2014-11-21 14:24:06.340 4028 INFO migrate.versioning.api [-] 47 -> 48...
2014-11-21 14:24:06.356 4028 INFO migrate.versioning.api [-] done
2014-11-21 14:24:06.356 4028 INFO migrate.versioning.api [-] 48 -> 49...
2014-11-21 14:24:06.371 4028 INFO migrate.versioning.api [-] done
2014-11-21 14:24:06.371 4028 INFO migrate.versioning.api [-] 49 -> 50...
2014-11-21 14:24:06.449 4028 INFO migrate.versioning.api [-] done
2014-11-21 14:24:06.449 4028 INFO migrate.versioning.api [-] 50 -> 51...
2014-11-21 14:24:06.487 4028 INFO migrate.versioning.api [-] done
2014-11-21 14:24:06.488 4028 INFO migrate.versioning.api [-] 51 -> 52...
2014-11-21 14:24:06.529 4028 INFO migrate.versioning.api [-] done
2014-11-21 14:24:06.529 4028 INFO migrate.versioning.api [-] 52 -> 53...
2014-11-21 14:24:07.105 4028 INFO migrate.versioning.api [-] done
2014-11-21 14:24:07.106 4028 INFO migrate.versioning.api [-] 53 -> 54...
2014-11-21 14:24:07.161 4028 INFO migrate.versioning.api [-] done
2014-11-21 14:24:07.162 4028 INFO migrate.versioning.api [-] 54 -> 55...
2014-11-21 14:24:07.241 4028 INFO migrate.versioning.api [-] done
2014-11-21 14:24:07.304 4028 INFO migrate.versioning.api [-] 0 -> 1...
2014-11-21 14:24:07.354 4028 INFO migrate.versioning.api [-] done
2014-11-21 14:24:07.354 4028 INFO migrate.versioning.api [-] 1 -> 2...
2014-11-21 14:24:07.405 4028 INFO migrate.versioning.api [-] done
```

If I query keystone.migrate_version:

```
MariaDB [keystone]> select * from migrate_version;
+---------------+-----------------------------------------------------------------------------+---------+
| repository_id | repository_path                                                             | version |
+---------------+-----------------------------------------------------------------------------+---------+
| keystone      | /usr/local/lib/python2.7/dist-packages/keystone/common/sql/migrate_repo     |      55 |
| revoke        | /usr/local/lib/python2.7/dist-packages/keystone/contrib/revoke/migrate_repo |       2 |
+---------------+-----------------------------------------------------------------------------+---------+
2 rows in set (0.01 sec)

MariaDB [keystone]>
```

I'm going to close this, but please re-open or give me a shout if you are still seeing this.

--Matt
