### ISSUE TITLE
[glance] glance client using public url for requests

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/ansible-lxc-rpc#475]
```
root@569037-infra01_utility_container-3c96c7c1:~# glance --debug image-list
curl -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'User-Agent: python-glanceclient' -H 'Connection: keep-alive' -H 'X-Auth-Token: {SHA1}ac99a1262a9b0a77ecc700d5edb0091a336aa986' -H 'Content-Type: application/octet-stream' http://10.17.255.180:9292/v1/images/detail?sort_key=name&sort_dir=asc&limit=20
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/shell.py", line 590, in main
    args.func(client, args)
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/v1/shell.py", line 107, in do_image_list
    utils.print_list(images, columns)
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/common/utils.py", line 121, in print_list
    for o in objs:
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/v1/images.py", line 196, in paginate
    images, resp = self._list(url, "images")
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/v1/images.py", line 62, in _list
    resp, body = self.client.get(url)
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/common/http.py", line 251, in get
    return self._request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/common/http.py", line 206, in _request
    raise exc.CommunicationError(message=message)
CommunicationError: Error finding address for http://10.17.255.180:9292/v1/images/detail?sort_key=name&sort_dir=asc&limit=20: ('Connection aborted.', error(113, 'No route to host'))
Error finding address for http://10.17.255.180:9292/v1/images/detail?sort_key=name&sort_dir=asc&limit=20: ('Connection aborted.', error(113, 'No route to host'))
root@569037-infra01_utility_container-3c96c7c1:~# glance --version
0.14.1
```

Looks like the python-glanceclient v 0.14.1 is trying to use the publicURL endpoint for internal requests

More to come

**Comment by claco** [comment]
Existing issue: https://github.com/rcbops/ansible-lxc-rpc/issues/473

**Comment by b3rn4rd0s** [comment]
Dup of #473.
