### ISSUE TITLE
[keystone] 404 when trying to pip install ooathlib>0.6

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/ansible-lxc-rpc#499]
Ansible Error

```
Result from run 5 is: {u'failed': True, u'finished': 1, u'cmd': u'/usr/local/bin/pip install /opt/keystone_2014.2', u'ansible_job_id': u'155219356134.3019', u'msg': u'stdout: Ignoring indexes: https://pypi.python.org/simple/\nUnpacking /opt/keystone_2014.2\n Running setup.py (path:/tmp/pip-fWcV9L-build/setup.py) egg_info for package from file:///opt/keystone_2014.2\n [pbr] Processing SOURCES.txt\n warning: LocalManifestMaker: standard file \'-c\' not found\n \n [pbr] In git context, generating filelist from git\n warning: no files found matching \'AUTHORS\'\n warning: no files found matching \'ChangeLog\'\n warning: no previously-included files matching \'*.pyc\' found anywhere in distribution\n warning: no files found matching \'AUTHORS\'\n warning: no files found matching \'ChangeLog\'\n warning: no files found matching \'CONTRIBUTING.txt\'\n warning: no files found matching \'run_tests.py\'\n warning: no files found matching \'TODO\'\n warning: no files found matching \'*.json\' under directory \'keystone\'\n warning: no files found matching \'*.pem\' under directory \'keystone\'\n warning: no files found matching \'*.sql\' under directory \'keystone\'\n warning: no previously-included files matching \'*.pyc\' found anywhere in distribution\n warning: no previously-included files matching \'*.log\' found anywhere in distribution\n warning: no previously-included files matching \'*.db\' found anywhere in distribution\n warning: no previously-included files matching \'*.swp\' found anywhere in distribution\nhttp://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\nRequirement already up-to-date: pbr>=0.6,!=0.7,<1.0 in /usr/local/lib/python2.7/dist-packages (from keystone==2014.2)\nhttp://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\nRequirement already up-to-date: WebOb>=1.2.3 in /usr/local/lib/python2.7/dist-packages (from keystone==2014.2)\nDownloading/unpacking eventlet>=0.15.1 (from keystone==2014.2)\n http://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\nDownloading/unpacking greenlet>=0.3.2 (from keystone==2014.2)\n http://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\n Downloading greenlet-0.4.5-cp27-none-linux_x86_64.whl\nhttp://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\nRequirement already up-to-date: netaddr>=0.7.12 in /usr/local/lib/python2.7/dist-packages (from keystone==2014.2)\nDownloading/unpacking PasteDeploy>=1.5.0 (from keystone==2014.2)\n http://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\n Downloading PasteDeploy-1.5.2-py2.py3-none-any.whl\nDownloading/unpacking Paste (from keystone==2014.2)\n http://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\nDownloading/unpacking Routes>=1.12.3,!=2.0 (from keystone==2014.2)\n http://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\n Downloading Routes-1.13-py2-none-any.whl\nhttp://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\nRequirement already up-to-date: six>=1.7.0 in /usr/local/lib/python2.7/dist-packages (from keystone==2014.2)\nDownloading/unpacking SQLAlchemy>=0.8.4,<=0.8.99,>=0.9.7,<=0.9.99 (from keystone==2014.2)\n http://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\nDownloading/unpacking sqlalchemy-migrate>=0.9.1,!=0.9.2 (from keystone==2014.2)\n http://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\nDownloading/unpacking passlib (from keystone==2014.2)\n http://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\nhttp://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\nRequirement already up-to-date: iso8601>=0.1.9 in /usr/local/lib/python2.7/dist-packages (from keystone==2014.2)\nhttp://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\nRequirement already up-to-date: python-keystoneclient>=0.10.0 in /usr/local/lib/python2.7/dist-packages (from keystone==2014.2)\nhttp://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\nRequirement already up-to-date: keystonemiddleware>=1.0.0 in /usr/local/lib/python2.7/dist-packages (from keystone==2014.2)\nhttp://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\nRequirement already up-to-date: oslo.config>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from keystone==2014.2)\nDownloading/unpacking oslo.messaging>=1.4.0 (from keystone==2014.2)\n http://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\nDownloading/unpacking oslo.db>=1.0.0 (from keystone==2014.2)\n http://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\nhttp://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\nRequirement already up-to-date: oslo.i18n>=1.0.0 in /usr/local/lib/python2.7/dist-packages (from keystone==2014.2)\nhttp://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\nRequirement already up-to-date: oslo.utils>=1.0.0 in /usr/local/lib/python2.7/dist-packages (from keystone==2014.2)\nhttp://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\nRequirement already up-to-date: Babel>=1.3 in /usr/local/lib/python2.7/dist-packages (from keystone==2014.2)\nDownloading/unpacking oauthlib>=0.6 (from keystone==2014.2)\n http://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available\n HTTP error 404 while getting http://rpc-slushee.rackspace.com/python_packages/proposed/juno/oauthlib-0.6.3-py2-none-any.whl (from http://rpc-slushee.rackspace.com/python_packages/proposed/juno/)\nCleaning up...\nException:\nTraceback (most recent call last):\n File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main\n status = self.run(options, args)\n File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run\n requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)\n File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 1197, in prepare_files\n do_download,\n File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 1375, in unpack_url\n self.session,\n File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 547, in unpack_http_url\n resp.raise_for_status()\n File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/models.py", line 795, in raise_for_status\n raise HTTPError(http_error_msg, response=self)\nHTTPError: 404 Client Error: Not Found\n\nStoring debug log for failure in /root/.pip/pip.log\n', u'changed': False, 'attempts': 5}
failed: [node91_keystone_container-c63d88c6] => {"ansible_job_id": "155219356134.3019", "attempts": 5, "changed": false, "cmd": "/usr/local/bin/pip install /opt/keystone_2014.2", "failed": true, "finished": 1}
msg: Task failed as maximum retries was encountered
```

Pip Log on Keystone Container

```
  HTTP error 404 while getting http://rpc-slushee.rackspace.com/python_packages/proposed/juno/oauthlib-0.6.3-py2-none-any.whl (from http://rpc-slushee.rackspace.com/python_packages/proposed/juno/)
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 547, in unpack_http_url
    resp.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/models.py", line 795, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found
```

Pip config on container

```
root@node121_keystone_container-eef23cc6:~# cat .pip/pip.conf 
[global]
no-index = true
pre = true
timeout = 120

[install]
upgrade = true
allow_all_external = true
find-links = 
    http://rpc-slushee.rackspace.com/python_packages/proposed/juno/
```

Local run of failing command

```
Downloading/unpacking oauthlib>=0.6 (from keystone==2014.2)
  http://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available
  HTTP error 404 while getting http://rpc-slushee.rackspace.com/python_packages/proposed/juno/oauthlib-0.6.3-py2-none-any.whl (from http://rpc-slushee.rackspace.com/python_packages/proposed/juno/)
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 547, in unpack_http_url
    resp.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/models.py", line 795, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found

Storing debug log for failure in /root/.pip/pip.log
```

**Comment by jacobwagner** [comment]
Just tried this again locally and it worked

```
Downloading/unpacking oauthlib>=0.6 (from keystone==2014.2)
  http://rpc-slushee.rackspace.com/python_packages/proposed/juno/ uses an insecure transport scheme (http). Consider using https if rpc-slushee.rackspace.com has it available
  Downloading oauthlib-0.7.1-py2-none-any.whl (110kB): 110kB downloaded
```

Seems like a transient bug. Need more stable cdn!

**Comment by claco** [comment]
@jacobwagner We have one, and working on getting that into a space on mirror.rackspace.  

You can also try:  http://rpc.cloudnull.io as the rpc repo url

**Comment by jacobwagner** [comment]
That worked. I dont know the timeline on the repo move but i would like to keep this open for regression testing purposes. I dont feel comfortable saying 10.0.0 is green if this is still going to exists as it was highly reproducable

**Comment by stevelle** [comment]
Related Issue #527

**Comment by cloudnull** [comment]
On all of the http://mirror.rackspace.com/rackspaceprivatecloud/python_packages/ releases I am seeing the package "oauthlib-0.7.X-py2-none-any.whl" being available. Is this still an issue for QE? If no can we close this issue?

**Comment by jacobwagner** [comment]
No i have not seen this issue since the "move away from cloudfiles" move....closing
