### ISSUE TITLE
Cannot boot VMs

### ISSUE THREAD

**Issue by jpmontez** [rcbops/ansible-lxc-rpc#561]
Currently, attempting to boot VMs fails with v10.0.0rc4. Nova Scheduler reports a timeout when connecting to the RabbitMQ cluster, however it succeeds almost immediately after a stack trace is returned:

```
root@569037-infra01_utility_container-3c96c7c1:~# nova boot --flavor 2 --image cirros --nic net-id=361133fa-5323-455e-8919-ca80f94d8f5a --poll test
+--------------------------------------+-----------------------------------------------+
| Property                             | Value                                         |
+--------------------------------------+-----------------------------------------------+
| OS-DCF:diskConfig                    | MANUAL                                        |
| OS-EXT-AZ:availability_zone          | nova                                          |
| OS-EXT-SRV-ATTR:host                 | -                                             |
| OS-EXT-SRV-ATTR:hypervisor_hostname  | -                                             |
| OS-EXT-SRV-ATTR:instance_name        | instance-00000107                             |
| OS-EXT-STS:power_state               | 0                                             |
| OS-EXT-STS:task_state                | scheduling                                    |
| OS-EXT-STS:vm_state                  | building                                      |
| OS-SRV-USG:launched_at               | -                                             |
| OS-SRV-USG:terminated_at             | -                                             |
| accessIPv4                           |                                               |
| accessIPv6                           |                                               |
| adminPass                            | 2GCuiFTWkhpz                                  |
| config_drive                         |                                               |
| created                              | 2014-11-17T20:43:36Z                          |
| flavor                               | m1.small (2)                                  |
| hostId                               |                                               |
| id                                   | 5455221a-425d-410e-9c41-befe7e3c802d          |
| image                                | cirros (f6260506-bbbb-4bc7-bd65-6d5dc7e70376) |
| key_name                             | -                                             |
| metadata                             | {}                                            |
| name                                 | test                                          |
| os-extended-volumes:volumes_attached | []                                            |
| progress                             | 0                                             |
| security_groups                      | default                                       |
| status                               | BUILD                                         |
| tenant_id                            | db64711efb34452d842eba8ad0e55ab7              |
| updated                              | 2014-11-17T20:43:36Z                          |
| user_id                              | 154a4300a59a45b3b128d5cd6916d59d              |
+--------------------------------------+-----------------------------------------------+

Server building... 0% complete
Error building server
ERROR (InstanceInErrorState): Timed out waiting for a reply to message ID 7fcba887e0ac429d88b882313a0722d5
```

```
# /var/log/nova/nova-compute.log
2014-11-17 17:40:27.319 9607 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 192.168.96.183:5672
2014-11-17 17:40:27.356 9607 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 192.168.96.183:5672
2014-11-17 17:40:27.434 9607 INFO oslo.messaging._drivers.impl_rabbit [-] Connected to AMQP server on 192.168.96.183:5672
2014-11-17 17:40:27.450 9607 INFO oslo.messaging._drivers.impl_rabbit [-] Connected to AMQP server on 192.168.96.183:5672
2014-11-17 17:40:29.817 9607 ERROR oslo.messaging._drivers.impl_rabbit [-] Failed to publish message to topic 'conductor': [Errno 104] Connection reset by peer
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit Traceback (most recent call last):
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/local/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_rabbit.py", line 655, in ensure
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit     return method()
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/local/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_rabbit.py", line 752, in _publish
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit     publisher = cls(self.conf, self.channel, topic=topic, **kwargs)
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/local/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_rabbit.py", line 378, in __init__
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit     **options)
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/local/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_rabbit.py", line 326, in __init__
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit     self.reconnect(channel)
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/local/lib/python2.7/dist-packages/oslo/messaging/_drivers/impl_rabbit.py", line 334, in reconnect
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit     routing_key=self.routing_key)
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 85, in __init__
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit     self.revive(self._channel)
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 218, in revive
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit     self.declare()
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 105, in declare
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit     self.exchange.declare()
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/local/lib/python2.7/dist-packages/kombu/entity.py", line 166, in declare
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit     nowait=nowait, passive=passive,
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/local/lib/python2.7/dist-packages/amqp/channel.py", line 613, in exchange_declare
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit     self._send_method((40, 10), args)
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/local/lib/python2.7/dist-packages/amqp/abstract_channel.py", line 56, in _send_method
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit     self.channel_id, method_sig, args, content,
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/local/lib/python2.7/dist-packages/amqp/method_framing.py", line 221, in write_method
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit     write_frame(1, channel, payload)
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/local/lib/python2.7/dist-packages/amqp/transport.py", line 182, in write_frame
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit     frame_type, channel, size, payload, 0xce,
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio.py", line 359, in sendall
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit     tail = self.send(data, flags)
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio.py", line 342, in send
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit     total_sent += fd.send(data[total_sent:], flags)
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit error: [Errno 104] Connection reset by peer
2014-11-17 17:40:29.817 9607 TRACE oslo.messaging._drivers.impl_rabbit
2014-11-17 17:40:29.819 9607 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2014-11-17 17:40:30.820 9607 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 192.168.96.183:5672
2014-11-17 17:40:30.835 9607 INFO oslo.messaging._drivers.impl_rabbit [-] Connected to AMQP server on 192.168.96.183:5672
```

From running a few commands, the RabbitMQ cluster seems fine:

```
root@569037-infra01_rabbit_mq_container-0ffc0429:~# rabbitmqctl cluster_status
Cluster status of node 'rabbit@569037-infra01_rabbit_mq_container-0ffc0429' ...
[{nodes,[{disc,['rabbit@569037-infra01_rabbit_mq_container-0ffc0429',
                'rabbit@569038-infra02_rabbit_mq_container-f027c373',
                'rabbit@569039-infra03_rabbit_mq_container-d00aa6a2']}]},
 {running_nodes,['rabbit@569039-infra03_rabbit_mq_container-d00aa6a2',
                 'rabbit@569038-infra02_rabbit_mq_container-f027c373',
                 'rabbit@569037-infra01_rabbit_mq_container-0ffc0429']},
 {cluster_name,<<"rpc">>},
 {partitions,[]}]
```

From a RabbitMQ container, there aren't immediately noticeable errors:

```
root@569037-infra01_rabbit_mq_container-0ffc0429:~# ip -s -s l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    RX: bytes  packets  errors  dropped overrun mcast
    337952     2201     0       0       0       0
    RX errors: length  crc     frame   fifo    missed
               0        0       0       0       0
    TX: bytes  packets  errors  dropped carrier collsns
    337952     2201     0       0       0       0
    TX errors: aborted fifo    window  heartbeat
               0        0       0       0
86: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 00:16:3e:54:fe:51 brd ff:ff:ff:ff:ff:ff
    RX: bytes  packets  errors  dropped overrun mcast
    3779222    1949     0       0       0       0
    RX errors: length  crc     frame   fifo    missed
               0        0       0       0       0
    TX: bytes  packets  errors  dropped carrier collsns
    228865     1560     0       0       0       0
    TX errors: aborted fifo    window  heartbeat
               0        0       0       0
88: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 00:16:3e:c2:28:c5 brd ff:ff:ff:ff:ff:ff
    RX: bytes  packets  errors  dropped overrun mcast
    15928660961 61063073 0       0       0       0
    RX errors: length  crc     frame   fifo    missed
               0        0       0       0       0
    TX: bytes  packets  errors  dropped carrier collsns
    15806840192 61560546 0       0       0       0
    TX errors: aborted fifo    window  heartbeat
               0        0       0       0
```

From the Compute container, I can ping and telnet to the necessary RabbitMQ container ports:

```
root@573972-compute01:~# ping -nc 3 192.168.96.183
PING 192.168.96.183 (192.168.96.183) 56(84) bytes of data.
64 bytes from 192.168.96.183: icmp_seq=1 ttl=64 time=0.698 ms
64 bytes from 192.168.96.183: icmp_seq=2 ttl=64 time=0.332 ms
64 bytes from 192.168.96.183: icmp_seq=3 ttl=64 time=0.346 ms

--- 192.168.96.183 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
rtt min/avg/max/mdev = 0.332/0.458/0.698/0.171 ms
```

```
root@573972-compute01:~# telnet 192.168.96.183 5672
Trying 192.168.96.183...
Connected to 192.168.96.183.
Escape character is '^]'.
^]
telnet> Connection closed.
```

You can also see the accepted requests from within the RabbitMQ container:

```
=INFO REPORT==== 17-Nov-2014::20:43:07 ===
accepting AMQP connection <0.7660.4> (192.168.96.137:44514 -> 192.168.99.39:5672)

=INFO REPORT==== 17-Nov-2014::20:43:37 ===
accepting AMQP connection <0.8262.4> (192.168.99.197:43137 -> 192.168.99.39:5672)
```

**Comment by mancdaz** [comment]
@Apsu @jpmontez could you update with any findings from the work you were doing on this

**Comment by mancdaz** [comment]
I'm not able to reproduce this issue...

**Comment by jacobwagner** [comment]
This lab was a update from 10.0.0rc3 to rc4. Since we are concerned with greenfield deploys for this release we will be tearing that lab down and rebuilding from scratch. I want to see if we can reproduce with a freenfield deploy.

**Comment by jpmontez** [comment]
After deploying `v10.0.0rc4`, this is still an issue. The error messages are the same.

**Comment by mancdaz** [comment]
@jacobwagner @jpmontez Not wanting to back and forth on this, I rebuilt a 10.0.0rc4 deployment today, and ran a bunch of tests.  I was able to build/delete 400 servers, and attach cinder volumes, without the occurrence of the rabbit connectivity issues you're seeing in the lab.

Perhaps this is an environment issue rather than a code issue? We can provide dev resource to help investigate

**Comment by mancdaz** [comment]
Update:

I did not see the same rabbitmq connectivity errors as originally reported.  There were still errors booting vm's however, and from `/var/log/nova/nova-compute`:

```
2014-11-18 21:44:35.836 10994 ERROR nova.compute.manager [req-a5c83af5-94ca-4e0f-b1ae-910a66e4f40a None] [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4] Instance failed to spawn
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4] Traceback (most recent call last):
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]   File "/usr/local/lib/python2.7/dist-packages/nova/compute/manager.py", line 2231, in _build_resources
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]     yield resources
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]   File "/usr/local/lib/python2.7/dist-packages/nova/compute/manager.py", line 2101, in _build_and_run_instance
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]     block_device_info=block_device_info)
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]   File "/usr/local/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 2615, in spawn
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]     admin_pass=admin_password)
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]   File "/usr/local/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 3005, in _create_image
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]     project_id=instance['project_id'])
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]   File "/usr/local/lib/python2.7/dist-packages/nova/virt/libvirt/imagebackend.py", line 208, in cache
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]     *args, **kwargs)
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]   File "/usr/local/lib/python2.7/dist-packages/nova/virt/libvirt/imagebackend.py", line 451, in create_image
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]     prepare_template(target=base, max_size=size, *args, **kwargs)
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]   File "/usr/local/lib/python2.7/dist-packages/nova/openstack/common/lockutils.py", line 272, in inner
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]     return f(*args, **kwargs)
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]   File "/usr/local/lib/python2.7/dist-packages/nova/virt/libvirt/imagebackend.py", line 198, in fetch_func_sync
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]     fetch_func(target=target, *args, **kwargs)
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]   File "/usr/local/lib/python2.7/dist-packages/nova/virt/libvirt/utils.py", line 452, in fetch_image
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]     max_size=max_size)
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]   File "/usr/local/lib/python2.7/dist-packages/nova/virt/images.py", line 79, in fetch_to_raw
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]     max_size=max_size)
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]   File "/usr/local/lib/python2.7/dist-packages/nova/virt/images.py", line 73, in fetch
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]     IMAGE_API.download(context, image_href, dest_path=path)
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]   File "/usr/local/lib/python2.7/dist-packages/nova/image/api.py", line 178, in download
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]     dst_path=dest_path)
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]   File "/usr/local/lib/python2.7/dist-packages/nova/image/glance.py", line 370, in download
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]     for chunk in image_chunks:
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]   File "/usr/local/lib/python2.7/dist-packages/glanceclient/common/utils.py", line 365, in integrity_iter
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]     for chunk in iter:
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 656, in generate
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]     raise ChunkedEncodingError(e)
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4] ChunkedEncodingError: ('Connection broken: IncompleteRead(12800 bytes read)', IncompleteRead(12800 bytes read))
2014-11-18 21:44:35.836 10994 TRACE nova.compute.manager [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4]
2014-11-18 21:44:35.842 10994 AUDIT nova.compute.manager [req-a5c83af5-94ca-4e0f-b1ae-910a66e4f40a None] [instance: d62ca448-10c4-4faa-9d46-768397ffbbc4] Terminating instance
```

This indicated an issue actually getting the glance image as a base image for nova to boot from.  Further investigation working directly with glance:

```
# glance image-download --file /tmp/cirros cirros
('Connection broken: IncompleteRead(12800 bytes read)', IncompleteRead(12800 bytes read))
```

Given that the glance back end is swift/cloudfiles, this indicates an issue with connectivity, or the image itself, in cloudfiles.

I re-uploaded the cirros image as cirros2 to check that the issue wasn't with a bad image in cloudfiles:

```
root@569037-infra01_glance_container-154feaa4:/tmp# wget http://download.cirros-cloud.net/0.3.3/cirros-0.3.3-x86_64-disk.img
---snip---
2014-11-20 11:08:30 (22.2 MB/s) - ‘cirros-0.3.3-x86_64-disk.img’ saved [13200896/13200896]

root@569037-infra01_glance_container-154feaa4:/tmp# glance image-create --container-format bare --disk-format qcow2 --file cirros-0.3.3-x86_64-disk.img --name cirros2
+------------------+--------------------------------------+
| Property         | Value                                |
+------------------+--------------------------------------+
| checksum         | 133eae9fb1c98f45894a4e60d8736619     |
| container_format | bare                                 |
| created_at       | 2014-11-20T11:08:45                  |
| deleted          | False                                |
| deleted_at       | None                                 |
| disk_format      | qcow2                                |
| id               | 7c37018e-fad8-45fd-a03d-459f64d2422b |
| is_public        | False                                |
| min_disk         | 0                                    |
| min_ram          | 0                                    |
| name             | cirros2                              |
| owner            | 80c9a4a3b8e2400d8ce6a2c28137a84a     |
| protected        | False                                |
| size             | 13200896                             |
| status           | active                               |
| updated_at       | 2014-11-20T11:08:49                  |
| virtual_size     | None                                 |
+------------------+--------------------------------------+

root@569037-infra01_glance_container-154feaa4:/tmp# glance image-download --file blah cirros2
root@569037-infra01_glance_container-154feaa4:/tmp# ll blah
-rw-r--r-- 1 root root 13200896 Nov 20 11:16 blah

```

This looked promising - I was able to get the image, whereas I wasn't with the original cirros.  Now to try booting from it :

```
root@569037-infra01:~# nova boot --image cirros2 --flavor 1 --nic net-id=970a5d66-0416-449c-851d-95d5e9a39fba darren-test4
+--------------------------------------+------------------------------------------------+
| Property                             | Value                                          |
+--------------------------------------+------------------------------------------------+
| OS-DCF:diskConfig                    | MANUAL                                         |
| OS-EXT-AZ:availability_zone          | nova                                           |
| OS-EXT-SRV-ATTR:host                 | -                                              |
| OS-EXT-SRV-ATTR:hypervisor_hostname  | -                                              |
| OS-EXT-SRV-ATTR:instance_name        | instance-00000016                              |
| OS-EXT-STS:power_state               | 0                                              |
| OS-EXT-STS:task_state                | scheduling                                     |
| OS-EXT-STS:vm_state                  | building                                       |
| OS-SRV-USG:launched_at               | -                                              |
| OS-SRV-USG:terminated_at             | -                                              |
| accessIPv4                           |                                                |
| accessIPv6                           |                                                |
| adminPass                            | tcARFw4QCFbQ                                   |
| config_drive                         |                                                |
| created                              | 2014-11-20T11:11:59Z                           |
| flavor                               | m1.tiny (1)                                    |
| hostId                               |                                                |
| id                                   | 42dd8c11-3526-433b-9cea-1169ad3ceb04           |
| image                                | cirros2 (7c37018e-fad8-45fd-a03d-459f64d2422b) |
| key_name                             | -                                              |
| metadata                             | {}                                             |
| name                                 | darren-test4                                   |
| os-extended-volumes:volumes_attached | []                                             |
| progress                             | 0                                              |
| security_groups                      | default                                        |
| status                               | BUILD                                          |
| tenant_id                            | 80c9a4a3b8e2400d8ce6a2c28137a84a               |
| updated                              | 2014-11-20T11:12:00Z                           |
| user_id                              | d60bd789823c4440a8cb0fdd305ba020               |
+--------------------------------------+------------------------------------------------+
root@569037-infra01:~# nova list
+--------------------------------------+--------------+--------+------------+-------------+---------------------+
| ID                                   | Name         | Status | Task State | Power State | Networks            |
+--------------------------------------+--------------+--------+------------+-------------+---------------------+
| 42dd8c11-3526-433b-9cea-1169ad3ceb04 | darren-test4 | ACTIVE | -          | Running     | private=172.31.0.10 |
+--------------------------------------+--------------+--------+------------+-------------+---------------------+
```

So, it seems the problem in this case was a corrupt cirros image in cloudfiles.  I don't know how the image got uploaded, from what source, but it was borken.

@jacobwagner @jpmontez can you try running your tests again and see how we go?

Probably related #571

**Comment by jpmontez** [comment]
It's odd that the image was corrupted; when I originally created it, I included the `--checksum` flag and the image's MD5 sum to prevent that from happening.

I'll retry the tests now and reply with some results.

**Comment by jpmontez** [comment]
:+1: LGTM

**Comment by Mudpuppy12** [comment]
I’m installing a lab and came across this:

TASK: [rpc_support_api | Create rpc_support security group] *******************

<172.27.236.95> ESTABLISH CONNECTION FOR USER: root

<172.27.236.95> REMOTE_MODULE command . /root/openrc neutron security-group-create rpc-support #USE_SHELL

<172.27.236.95> EXEC ['ssh', '-C', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=120', u'172.27.236.95', u"/bin/sh -c 'LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python'"]

failed: [controller06_utility_container-472a9300] => {"changed": false, "cmd": ". /root/openrc\nneutron security-group-create rpc-support", "delta": "0:00:24.105298", "end": "2014-12-02 00:19:42.585559", "failed": true, "failed_when_result": true, "rc": 1, "start": "2014-12-02 00:19:18.480261", "stdout_lines": []}

stderr: Unable to establish connection to http://72.4.117.92:9696/v2.0/security-groups.json

72.4.117.92 is the external LB address. Should it be trying to connect to the internal LB address?

I’m not sure why it’s pulling the external address. Here is the debug below.

From the container:

root@controller06_utility_container-472a9300:~# neutron security-group-list -vvvvv

DEBUG: keystoneclient.session REQ: curl -i -X GET http://172.27.236.31:5000/v2.0 -H "Accept: application/json" -H "User-Agent: python-keystoneclient"

DEBUG: keystoneclient.session RESP: [200] content-length: 616 vary: X-Auth-Token keep-alive: timeout=5, max=100 server: Apache/2.4.7 (Ubuntu) connection: Keep-Alive date: Tue, 02 Dec 2014 00:37:08 GMT content-type: application/json

RESP BODY: {"version": {"status": "stable", "updated": "2014-04-17T00:00:00Z", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v2.0+json"}, {"base": "application/xml", "type": "application/vnd.openstack.identity-v2.0+xml"}], "id": "v2.0", "links": [{"href": "http://172.27.236.31:5000/v2.0/", "rel": "self"}, {"href": "http://docs.openstack.org/api/openstack-identity-service/2.0/content/", "type": "text/html", "rel": "describedby"}, {"href": "http://docs.openstack.org/api/openstack-identity-service/2.0/identity-dev-guide-2.0.pdf", "type": "application/pdf", "rel": "describedby"}]}}

DEBUG: stevedore.extension found extension EntryPoint.parse('table = cliff.formatters.table:TableFormatter')

DEBUG: stevedore.extension found extension EntryPoint.parse('csv = cliff.formatters.commaseparated:CSVLister')

DEBUG: neutronclient.neutron.v2_0.securitygroup.ListSecurityGroup get_data(Namespace(columns=[], fields=[], formatter='table', max_width=0, page_size=None, quote_mode='nonnumeric', request_format='json', show_details=False, sort_dir=[], sort_key=[]))

DEBUG: keystoneclient.auth.identity.v2 Making authentication request to http://172.27.236.31:5000/v2.0/tokens

DEBUG: keystoneclient.session REQ: curl -i -X GET http://72.4.117.92:9696/v2.0/security-groups.json -H "User-Agent: python-neutronclient" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}0e0c25b77f4bc78c83567c41a550d1237de4b568"
