### ISSUE TITLE
Swift parameter causes inventory generator error

### ISSUE THREAD

**Issue by ionosphere80** [rcbops/ansible-lxc-rpc#564]
The "weight" parameter in swift.yml causes the following inventory generator error:

Traceback (most recent call last):
  File "./dynamic_inventory.py", line 845, in <module>
    main()
  File "./dynamic_inventory.py", line 811, in main
    user_defined_config
  File "./dynamic_inventory.py", line 493, in container_skel_load
    value.get('is_metal', False)
  File "./dynamic_inventory.py", line 346, in _add_container_hosts
    host_options
  File "./dynamic_inventory.py", line 263, in _append_to_host_groups
    if 'limit_container_types' in options:
TypeError: argument of type 'int' is not iterable

**Comment by andymcc** [comment]
@ionosphere80 can you give a link to your swift.yml?

**Comment by ionosphere80** [comment]
Sure...

https://gist.github.com/ionosphere80/b80a48f8934d6fbbcc8f

**Comment by ionosphere80** [comment]
I'm going to test a swift.yml example from @andymcc to see if it resolves the issue.
