### ISSUE TITLE
Cinder create volume from image is unable to find image

### ISSUE THREAD

**Issue by jcourtois** [rcbops/ansible-lxc-rpc#571]
In SAT6 lab 1 running RPC 10.0.4rc, when trying to create a volume from an existing image in glance, the volume ends in an error state.

The command used is:
`cinder --debug create --image-id c93c78a8-1b88-44ba-b94d-12421663258d --volume-type lvm 50`

The most important part of the stack trace is:

```
d5036e003bc643d4be06361ce0f31990 - - -] Exception during message handling: Failed to copy image to volume: HTTPInternalServerError (HTTP 500)
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher Traceback (most recent call last):
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/oslo/messaging/rpc/dispatcher.py", line 134, in _dispatch_and_reply
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher     incoming.message))
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/oslo/messaging/rpc/dispatcher.py", line 177, in _dispatch
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher     return self._do_dispatch(endpoint, method, ctxt, args)
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/oslo/messaging/rpc/dispatcher.py", line 123, in _do_dispatch
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher     result = getattr(endpoint, method)(ctxt, **new_args)
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/osprofiler/profiler.py", line 105, in wrapper
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher     return f(*args, **kwargs)
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/cinder/volume/manager.py", line 381, in create_volume
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher     _run_flow()
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/cinder/volume/manager.py", line 374, in _run_flow
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher     flow_engine.run()
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/taskflow/engines/action_engine/engine.py", line 99, in run
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher     for _state in self.run_iter():
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/taskflow/engines/action_engine/engine.py", line 156, in run_iter
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher     misc.Failure.reraise_if_any(failures.values())
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/taskflow/utils/misc.py", line 733, in reraise_if_any
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher     failures[0].reraise()
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/taskflow/utils/misc.py", line 740, in reraise
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher     six.reraise(*self._exc_info)
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/taskflow/engines/action_engine/executor.py", line 35, in _execute_task
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher     result = task.execute(**arguments)
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/cinder/volume/flows/manager/create_volume.py", line 638, in execute
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher     **volume_spec)
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/cinder/volume/flows/manager/create_volume.py", line 590, in _create_from_image
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher     image_id, image_location, image_service)
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher   File "/usr/local/lib/python2.7/dist-packages/cinder/volume/flows/manager/create_volume.py", line 504, in _copy_image_to_volume
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher     raise exception.ImageCopyFailure(reason=ex)
2014-11-18 16:59:18.167 845 TRACE oslo.messaging.rpc.dispatcher ImageCopyFailure: Failed to copy image to volume: HTTPInternalServerError (HTTP 500)
```

More complete logs are viewable [here](https://gist.github.com/jcourtois/ecb77a9c659c428bf36e). Please let me know if I can provide more information.

**Comment by jcourtois** [comment]
Just a note – may or may not be relevant – I am noticing that I cannot directly SSH into glance containers from the deployment host. SSH into the host node, then attaching to the container works, however.

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
[redacted]
Please contact your system administrator.
Add correct host key in /root/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /root/.ssh/known_hosts:77
  remove with: ssh-keygen -f "/root/.ssh/known_hosts" -R node121_glance_container-752c692c
ECDSA host key for node121_glance_container-752c692c has changed and you have requested strict checking.
Host key verification failed.
```

**Comment by jacobwagner** [comment]
The ssh issue is my teardown play not removing bad host keys from the deployment servers known hosts...i will fix that.

**Comment by mattt416** [comment]
Hi @jcourtois,

@mancdaz tested this while investigating issue #561 and determined that this issue was related to the bad image in glance.  Once a new image was uploaded he was able to `cinder --debug create --image-id <image. --volume-type lvm 50` fine.

I'm going to go ahead and mark this as not a bug, but please grab me if you have any follow-up information or require further assistance.

Thanks!

--Matt
