### ISSUE TITLE
Jenkins jobs queuing indefinitely

### ISSUE THREAD

**Issue by hughsaunders** [rcbops/ansible-lxc-rpc#657]
![screen shot 2014-11-27 at 10 26 04](https://cloud.githubusercontent.com/assets/253506/5215473/d546c606-761f-11e4-8187-8e799a205695.png)

Exception in logs: 

```
Nov 27, 2014 9:09:25 AM SEVERE hudson.triggers.SafeTimerTask run
Timer task hudson.model.Queue$MaintainTask@3345e4e failed
java.lang.ClassCastException: org.acegisecurity.providers.UsernamePasswordAuthenticationToken cannot be cast to org.jenkinsci.plugins.GithubAuthenticationToken
    at org.jenkinsci.plugins.GithubSecurityRealm.loadUserByUsername(GithubSecurityRealm.java:541)
    at org.jenkinsci.plugins.GithubSecurityRealm$2.loadUserByUsername(GithubSecurityRealm.java:493)
    at jenkins.security.ImpersonatingUserDetailsService.loadUserByUsername(ImpersonatingUserDetailsService.java:32)
    at hudson.model.User.impersonate(User.java:282)
    at org.jenkinsci.plugins.authorizeproject.strategy.SpecificUsersAuthorizationStrategy.authenticate(SpecificUsersAuthorizationStrategy.java:108)
    at org.jenkinsci.plugins.authorizeproject.AuthorizeProjectProperty.authenticate(AuthorizeProjectProperty.java:89)
    at org.jenkinsci.plugins.authorizeproject.ProjectQueueItemAuthenticator.authenticate(ProjectQueueItemAuthenticator.java:73)
    at hudson.model.Queue$Item.authenticate(Queue.java:1517)
    at hudson.model.Node.canTake(Node.java:345)
    at hudson.model.Queue$JobOffer.canTake(Queue.java:269)
    at hudson.model.Queue.maintain(Queue.java:1041)
    at hudson.model.Queue$MaintainTask.doRun(Queue.java:2009)
    at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:54)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by odyssey4me** [comment]
Vote for the issue here: https://issues.jenkins-ci.org/browse/JENKINS-25791

**Comment by hughsaunders** [comment]
Worked around by disabling jenkins authorizeproject plugin
