### ISSUE TITLE
Keystone DB Sync Fails - No module named prettytable

### ISSUE THREAD

**Issue by byronmccollum** [rcbops/ansible-lxc-rpc#95]
```
 ___________________________________________________
< TASK: keystone_setup | Perform a Keystone DB sync >
 ---------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


failed: [infra1_keystone_container-9e358377] => {"changed": true, "cmd": ["keystone-manage", "db_sync"], "delta": "0:00:00.574404", "end": "2014-09-08 22:18:15.542870", "rc": 1, "st
art": "2014-09-08 22:18:14.968466"}
stderr: Traceback (most recent call last):
  File "/usr/local/bin/keystone-manage", line 37, in <module>
    from keystone import cli
  File "/usr/local/lib/python2.7/dist-packages/keystone/cli.py", line 27, in <module>
    from keystone import token
  File "/usr/local/lib/python2.7/dist-packages/keystone/token/__init__.py", line 17, in <module>
    from keystone.token import controllers
  File "/usr/local/lib/python2.7/dist-packages/keystone/token/controllers.py", line 18, in <module>
    from keystoneclient.common import cms
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/__init__.py", line 27, in <module>
    from keystoneclient import access
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/access.py", line 21, in <module>
    from keystoneclient import service_catalog
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/service_catalog.py", line 24, in <module>
    from keystoneclient import utils
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/utils.py", line 20, in <module>
    import prettytable
ImportError: No module named prettytable

FATAL: all hosts have already failed -- aborting
```

If I attach to the Keystone containers, and manually `pip install prettytable`, things move along...

```
root@infra1_keystone_container-9e358377:/opt/keystone_stable_icehouse# keystone-manage db_sync
Traceback (most recent call last):
  File "/usr/local/bin/keystone-manage", line 37, in <module>
    from keystone import cli
  File "/usr/local/lib/python2.7/dist-packages/keystone/cli.py", line 27, in <module>
    from keystone import token
  File "/usr/local/lib/python2.7/dist-packages/keystone/token/__init__.py", line 17, in <module>
    from keystone.token import controllers
  File "/usr/local/lib/python2.7/dist-packages/keystone/token/controllers.py", line 18, in <module>
    from keystoneclient.common import cms
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/__init__.py", line 27, in <module>
    from keystoneclient import access
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/access.py", line 21, in <module>
    from keystoneclient import service_catalog
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/service_catalog.py", line 24, in <module>
    from keystoneclient import utils
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/utils.py", line 20, in <module>
    import prettytable
ImportError: No module named prettytable
root@infra1_keystone_container-9e358377:/opt/keystone_stable_icehouse# pip install prettytable
Downloading/unpacking prettytable
  Downloading prettytable-0.7.2.tar.bz2
  Running setup.py (path:/tmp/pip_build_root/prettytable/setup.py) egg_info for package prettytable

Installing collected packages: prettytable
  Running setup.py install for prettytable

Successfully installed prettytable
Cleaning up...
root@infra1_keystone_container-9e358377:/opt/keystone_stable_icehouse# keystone-manage db_sync
2014-09-09 08:35:11.390 2238 INFO migrate.versioning.api [-] 0 -> 1... 
2014-09-09 08:35:11.493 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:11.494 2238 INFO migrate.versioning.api [-] 1 -> 2... 
2014-09-09 08:35:11.528 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:11.528 2238 INFO migrate.versioning.api [-] 2 -> 3... 
2014-09-09 08:35:11.559 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:11.560 2238 INFO migrate.versioning.api [-] 3 -> 4... 
2014-09-09 08:35:11.587 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:11.588 2238 INFO migrate.versioning.api [-] 4 -> 5... 
2014-09-09 08:35:11.684 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:11.685 2238 INFO migrate.versioning.api [-] 5 -> 6... 
2014-09-09 08:35:11.700 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:11.701 2238 INFO migrate.versioning.api [-] 6 -> 7... 
2014-09-09 08:35:11.755 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:11.755 2238 INFO migrate.versioning.api [-] 7 -> 8... 
2014-09-09 08:35:11.767 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:11.767 2238 INFO migrate.versioning.api [-] 8 -> 9... 
2014-09-09 08:35:11.825 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:11.826 2238 INFO migrate.versioning.api [-] 9 -> 10... 
2014-09-09 08:35:11.844 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:11.844 2238 INFO migrate.versioning.api [-] 10 -> 11... 
2014-09-09 08:35:11.892 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:11.893 2238 INFO migrate.versioning.api [-] 11 -> 12... 
2014-09-09 08:35:11.910 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:11.910 2238 INFO migrate.versioning.api [-] 12 -> 13... 
2014-09-09 08:35:11.954 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:11.954 2238 INFO migrate.versioning.api [-] 13 -> 14... 
2014-09-09 08:35:12.014 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.014 2238 INFO migrate.versioning.api [-] 14 -> 15... 
2014-09-09 08:35:12.155 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.155 2238 INFO migrate.versioning.api [-] 15 -> 16... 
2014-09-09 08:35:12.284 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.285 2238 INFO migrate.versioning.api [-] 16 -> 17... 
2014-09-09 08:35:12.334 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.334 2238 INFO migrate.versioning.api [-] 17 -> 18... 
2014-09-09 08:35:12.375 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.375 2238 INFO migrate.versioning.api [-] 18 -> 19... 
2014-09-09 08:35:12.390 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.390 2238 INFO migrate.versioning.api [-] 19 -> 20... 
2014-09-09 08:35:12.418 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.418 2238 INFO migrate.versioning.api [-] 20 -> 21... 
2014-09-09 08:35:12.450 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.450 2238 INFO migrate.versioning.api [-] 21 -> 22... 
2014-09-09 08:35:12.464 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.464 2238 INFO migrate.versioning.api [-] 22 -> 23... 
2014-09-09 08:35:12.505 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.505 2238 INFO migrate.versioning.api [-] 23 -> 24... 
2014-09-09 08:35:12.531 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.531 2238 INFO migrate.versioning.api [-] 24 -> 25... 
2014-09-09 08:35:12.572 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.573 2238 INFO migrate.versioning.api [-] 25 -> 26... 
2014-09-09 08:35:12.642 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.642 2238 INFO migrate.versioning.api [-] 26 -> 27... 
2014-09-09 08:35:12.674 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.675 2238 INFO migrate.versioning.api [-] 27 -> 28... 
2014-09-09 08:35:12.681 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.681 2238 INFO migrate.versioning.api [-] 28 -> 29... 
2014-09-09 08:35:12.708 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.708 2238 INFO migrate.versioning.api [-] 29 -> 30... 
2014-09-09 08:35:12.714 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.714 2238 INFO migrate.versioning.api [-] 30 -> 31... 
2014-09-09 08:35:12.733 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.733 2238 INFO migrate.versioning.api [-] 31 -> 32... 
2014-09-09 08:35:12.759 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.759 2238 INFO migrate.versioning.api [-] 32 -> 33... 
2014-09-09 08:35:12.775 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.776 2238 INFO migrate.versioning.api [-] 33 -> 34... 
2014-09-09 08:35:12.800 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.801 2238 INFO migrate.versioning.api [-] 34 -> 35... 
2014-09-09 08:35:12.826 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.826 2238 INFO migrate.versioning.api [-] 35 -> 36... 
2014-09-09 08:35:12.840 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.840 2238 INFO migrate.versioning.api [-] 36 -> 37... 
2014-09-09 08:35:12.855 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.856 2238 INFO migrate.versioning.api [-] 37 -> 38... 
2014-09-09 08:35:12.897 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.897 2238 INFO migrate.versioning.api [-] 38 -> 39... 
2014-09-09 08:35:12.931 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.931 2238 INFO migrate.versioning.api [-] 39 -> 40... 
2014-09-09 08:35:12.967 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.968 2238 INFO migrate.versioning.api [-] 40 -> 41... 
2014-09-09 08:35:12.986 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:12.986 2238 INFO migrate.versioning.api [-] 41 -> 42... 
2014-09-09 08:35:13.011 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:13.012 2238 INFO migrate.versioning.api [-] 42 -> 43... 
2014-09-09 08:35:13.020 2238 INFO migrate.versioning.api [-] done
2014-09-09 08:35:13.020 2238 INFO migrate.versioning.api [-] 43 -> 44... 
2014-09-09 08:35:13.045 2238 INFO migrate.versioning.api [-] done
root@infra1_keystone_container-9e358377:/opt/keystone_stable_icehouse# 
```

**Comment by cloudnull** [comment]
While I want to say that this should be resolved this issue is directly related to https://github.com/rcbops/ansible-lxc-rpc/issues/31.  That said, please let us know that last SHA of the stable/icehouse branch that is bing cloned down so that we can ensure this is properly addressed.

**Comment by byronmccollum** [comment]
@cloudnull This appears to be resolved!
